from ultralytics import YOLO
import torch
print(torch.cuda.is_available())
model = YOLO("YOLOv8m-worldv2.pt")
model.set_classes([
    "salt",
    "sugar",
    "flour",
    "water",
    "butter",
    "egg",
    "milk",
    "olive oil",
    "baking powder",
    "vanilla extract",
    "garlic",
    "onion",
    "tomato",
    "lemon juice",
    "pepper",
    "cheese",
    "chicken",
    "beef",
    "rice",
    "pasta",
    "yeast",
    "honey",
    "soy sauce",
    "carrot",
    "celery",
    "potato",
    "vinegar",
    "parsley",
    "basil",
    "thyme",
    "cinnamon",
    "nutmeg",
    "paprika",
    "oregano",
    "ginger",
    "chili powder",
    "mustard",
    "ketchup",
    "mayonnaise",
    "brown sugar",
    "baking soda",
    "cream cheese",
    "sour cream",
    "cream",
    "cocoa powder",
    "chocolate chips",
    "bread",
    "spinach",
    "bell pepper",
    "mushroom",
    "corn",
    "peas",
    "green beans",
    "broccoli",
    "zucchini",
    "cucumber",
    "lettuce",
    "cabbage",
    "avocado",
    "apple",
    "banana",
    "strawberry",
    "blueberry",
    "raspberry",
    "pineapple",
    "mango",
    "broth",
    "wine",
    "beer",
    "fish",
    "shrimp",
    "pork",
    "bacon",
    "sausage",
    "tofu",
    "milk",
    "peanut butter",
    "jam",
    "maple syrup",
    "molasses",
    "corn syrup",
    "oats",
    "pancake mix",
    "cereal",
    "tortilla",
    "pita bread",
    "bagel",
    "chips",
    "nuts",
    "seeds",
    "raisins",
    "chickpeas",
    "lentils",
    "kidney beans",
    "black beans"
])
# results = model.train(data="lvis.yaml", epochs=100, imgsz=640, device="gpu")
model.export(format="onnx") 

