import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { getSession } from "@/auth";
import Providers from "./providers";
import { useState } from "react";
import LoginButton from "./components/LoginButton";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <Navbar />
          <LoginButton />
          {children}
        </Providers>
      </body>
    </html>
  );
}
